layout_spectrum: 0.9446809
author:
  name: Daniel Atwood
name: 'Moongate '
content_rating:
  adult: false
title: 'Bermudas guide to local independent music '
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.06595745
color:
  brandStrength: 0.1991130809765309
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.6021277
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
